import "server-only";

export const LIMITATION_DISCLAIMER =
  "Numbers from {zone} have not been updated since {date}. The gap likely reflects access constraints rather than an absence of cases.";

export const SOURCE_ATTR_PATTERN = "Source: {authority}, {date}. Click to view evidence.";

export const AI_GENERATED_LABEL =
  "Summary generated by Claude Sonnet 4.6. Extracted numbers are linked to their source sentences below.";

export const HAND_WRITTEN_LABEL =
  "Hand-written summary. Extracted numbers link to their source sentences.";

export const NO_OPERATIONAL_USE =
  "If you are a field epidemiologist needing an operational tool, use Go.Data, SORMAS, or DHIS2 Tracker.";

export const PROVENANCE_HOOK =
  "Hover any figure on this page to see the exact sentence from the source document it was extracted from.";

export const LANDING_HOOK = "Hover any figure for its source sentence.";

export const DISAGREEMENT_TEMPLATE =
  "WHO DON ({date1}): {n1} suspected. WHO AFRO sitrep ({date2}): {n2} suspected. The difference reflects reporting lag and differing case inclusion criteria.";

export const ABOUT_AUTHOR_LINE =
  "Built by an MD student at the University of Western Australia as a side project. Evaluated accordingly.";
